### ISSUE TITLE
Computing power allocation

### ISSUE THREAD

**Issue by Wulinaoano** [marmotlab/codebase_SYLPH#1]
In the process of running this project, I would like to further understand some details about the computing power requirements in order to better plan the experimental resources：
1.What hardware configuration did you use when running codebase_SYLPH (GPU model, video memory size, number of CPU cores, etc.)
2.How much time did you spend training over the course of the project?
3.Do you have a recommended minimum hardware configuration or optimization if you need to reproduce all the experimental results of the project?

**Comment by ChengyangHE** [comment]
Hi,
Thank you for your interest about our work. Here are the answers of your questions:
1. We use NIVDIA RTX 3090; 32GB for ram; and 32 cores.
2. We use about 3days for the training process.
3. I think most newer GPUs can meet the training requirements. The only thing should be noted that the number of CPU cores should be greater than 16.
Hope these information can help with your work. (btw, If it is useful to you, I would be grateful if you could click a star :)

**Comment by ChengyangHE** [comment]
> In the process of running this project, I would like to further understand some details about the computing power requirements in order to better plan the experimental resources： 1.What hardware configuration did you use when running codebase_SYLPH (GPU model, video memory size, number of CPU cores, etc.) 2.How much time did you spend training over the course of the project? 3.Do you have a recommended minimum hardware configuration or optimization if you need to reproduce all the experimental results of the project?

Hi,
Thank you for your interest about our work. Here are the answers of your questions:

    We use NIVDIA RTX 3090; 32GB for ram; and 32 cores.
    We use about 3days for the training process.
    I think most newer GPUs can meet the training requirements. The only thing should be noted that the number of CPU cores should be greater than 16.
    Hope these information can help with your work. (btw, If it is useful to you, I would be grateful if you could click a star :)

**Comment by Wulinaoano** [comment]
Thank you for your prompt reply to my inquiry. We appreciate your prompt response and help us move forward efficiently.



At 2024-12-12 17:37:27, "He Chengyang" ***@***.***> wrote:

In the process of running this project, I would like to further understand some details about the computing power requirements in order to better plan the experimental resources： 1.What hardware configuration did you use when running codebase_SYLPH (GPU model, video memory size, number of CPU cores, etc.) 2.How much time did you spend training over the course of the project? 3.Do you have a recommended minimum hardware configuration or optimization if you need to reproduce all the experimental results of the project?

Hi,
Thank you for your interest about our work. Here are the answers of your questions:

We use NIVDIA RTX 3090; 32GB for ram; and 32 cores.
We use about 3days for the training process.
I think most newer GPUs can meet the training requirements. The only thing should be noted that the number of CPU cores should be greater than 16.
Hope these information can help with your work. (btw, If it is useful to you, I would be grateful if you could click a star :)
